FROM golang:1.13.5
ENV GOPATH /go
ENV PATH $PATH:$GOPATH/bin

RUN mkdir -p /go/src/github.com/Sowiriro/Manaphy
COPY . /go/src/github.com/Sowiriro/Manaphy
WORKDIR /go/src/github.com/Sowiriro/Manaphy
ENV PATH $PATH:/go/src/github.com/Sowiriro/Manaphy
ENV GO111MODULE=on

RUN go mod init
RUN go mod tidy
RUN go get -v github.com/rubenv/sql-migrate/...
RUN go get github.com/pilu/fresh

EXPOSE 8000
CMD ["go", "run", "main.go", "movie.go", "auth.go", "err.go"]
# CMD ["realize", "start", "--run"]
# CMD ["fresh"]
